const NotifyType = [
  "ORDER_ACCEPTED_BY_TRANSPORTER",
  "ORDER_REJECTED_BY_TRANSPORTER",
  "ORDER_ACCEPTED_BY_VENDOR",
  "ORDER_REJECTED_BY_VENDOR",
  "ORDER_ACCEPTED_BY_CUSTOMER",
  "ORDER_REJECTED_BY_CUSTOMER",
  "ORDER_DELIVERED",
];
export default  NotifyType